/**
 * Inline the built SPA into a TypeScript module, so the compiled binary carries the web UI.
 *
 *   bun run scripts/embed-web-assets.ts
 *
 * Runs after `vite build`. Reads `apps/web/dist` and writes `packages/cli/src/generated/webAssets.ts`.
 *
 * Inlining rather than reading files at runtime, or relying on Bun's embedded-file path resolution, because
 * the same code path then works three ways with no branching: from source, from the compiled binary, and
 * under vitest. A binary that looked for files beside itself would work until someone moved it.
 *
 * Base64 for every asset, including text. Emitting JS and CSS as template literals would mean escaping
 * backticks and `${`, and getting that subtly wrong would corrupt the bundle rather than fail loudly.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, join, posix, relative, sep } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const DIST = join(ROOT, "apps", "web", "dist");
const OUT_DIR = join(ROOT, "packages", "cli", "src", "generated");
const OUT = join(OUT_DIR, "webAssets.ts");

/** Kept in step with `serve/assets.ts`, which uses the same list for files read off disk. */
const TYPES: Record<string, string> = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".ico": "image/x-icon",
    ".webp": "image/webp",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".map": "application/json; charset=utf-8"
};

function walk(dir: string): string[] {
    return readdirSync(dir).flatMap((name) => {
        const path = join(dir, name);
        return statSync(path).isDirectory() ? walk(path) : [path];
    });
}

function main(): void {
    if (!existsSync(DIST)) {
        console.error(
            `✗ ${relative(ROOT, DIST)} does not exist.\n` +
                `  Run the SPA build first: bun run --cwd apps/web build`
        );
        process.exit(1);
    }

    const files = walk(DIST).sort();
    if (files.length === 0) {
        console.error(`✗ ${relative(ROOT, DIST)} is empty, so there is nothing to embed.`);
        process.exit(1);
    }

    if (!files.some((file) => file.endsWith(`${sep}index.html`))) {
        // Without an entry document the server has nothing to fall back to for client-side routes, and
        // every deep link would 404. Better to fail the build than ship that.
        console.error("✗ no index.html in the build output — the SPA entry document is missing.");
        process.exit(1);
    }

    const entries: string[] = [];
    let bytes = 0;

    for (const file of files) {
        // Served paths are URL paths, so they use forward slashes whatever the build ran on.
        const route = `/${posix.join(...relative(DIST, file).split(sep))}`;
        const body = readFileSync(file);
        bytes += body.length;

        const type = TYPES[extname(file).toLowerCase()] ?? "application/octet-stream";
        // Vite names everything but the entry document `name-HASH.ext`, and a hashed name can never change
        // its contents, so it is safe to cache forever.
        const immutable = /-[A-Za-z0-9_-]{8,}\.[a-z0-9]+$/.test(file);

        entries.push(
            `    ${JSON.stringify(route)}: {\n` +
                `        type: ${JSON.stringify(type)},\n` +
                `        immutable: ${immutable},\n` +
                `        base64: ${JSON.stringify(body.toString("base64"))}\n` +
                `    }`
        );
    }

    mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(
        OUT,
        `// Generated by scripts/embed-web-assets.ts. Do not edit, and do not commit: this file is\n` +
            `// gitignored, and \`webAssets.d.ts\` beside it is what keeps the import typechecking when it is\n` +
            `// absent. Regenerate with \`bun run build:web\`.\n` +
            `\n` +
            `export const ASSETS: Record<string, { type: string; immutable: boolean; base64: string }> = {\n` +
            `${entries.join(",\n")}\n` +
            `};\n`,
        "utf8"
    );

    const generated = statSync(OUT).size;
    console.log(
        `✓ embedded ${files.length} file${files.length === 1 ? "" : "s"} ` +
            `(${(bytes / 1024).toFixed(1)} kB → ${(generated / 1024).toFixed(1)} kB of base64) ` +
            `into ${relative(ROOT, OUT)}`
    );
}

main();
